# Copyright (c) Soundscape Community Contributors.
# Generated by Django 5.2.4 on 2026-02-24 16:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0003_team_teammembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.folder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='api.folder'),
        ),
        migrations.CreateModel(
            name='FolderTeamPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('access', models.CharField(choices=[('read', 'Read'), ('write', 'Write')], max_length=10)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_permissions', to='api.folder')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_team_permissions', to='users.team')),
            ],
        ),
        migrations.CreateModel(
            name='FolderUserPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('access', models.CharField(choices=[('read', 'Read'), ('write', 'Write')], max_length=10)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permissions', to='api.folder')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folder_user_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('owner', 'parent', 'name'), name='unique_folder_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='unique_root_folder_name_global'),
        ),
        migrations.AddConstraint(
            model_name='folderteampermission',
            constraint=models.UniqueConstraint(fields=('folder', 'team'), name='unique_folder_team_permission'),
        ),
        migrations.AddConstraint(
            model_name='folderuserpermission',
            constraint=models.UniqueConstraint(fields=('folder', 'user'), name='unique_folder_user_permission'),
        ),
    ]
