# Generated by Django 5.2.4 on 2026-02-24 13:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
        ('users', '0003_group_groupmembership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.TextField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='folders', to=settings.AUTH_USER_MODEL)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='api.folder')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='folder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to='api.folder'),
        ),
        migrations.CreateModel(
            name='FolderPermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('principal_type', models.CharField(choices=[('user', 'User'), ('group', 'Group')], max_length=10)),
                ('access', models.CharField(choices=[('read', 'Read'), ('write', 'Write')], max_length=10)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='api.folder')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to='users.group')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', False)), fields=('owner', 'parent', 'name'), name='unique_folder_name_per_parent'),
        ),
        migrations.AddConstraint(
            model_name='folder',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('name',), name='unique_root_folder_name_global'),
        ),
        migrations.AddConstraint(
            model_name='folderpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('principal_type', 'user')), fields=('folder', 'user'), name='unique_folder_user_permission'),
        ),
        migrations.AddConstraint(
            model_name='folderpermission',
            constraint=models.UniqueConstraint(condition=models.Q(('principal_type', 'group')), fields=('folder', 'group'), name='unique_folder_group_permission'),
        ),
        migrations.AddConstraint(
            model_name='folderpermission',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('user__isnull', False), ('group__isnull', True)), models.Q(('user__isnull', True), ('group__isnull', False)), _connector='OR'), name='folder_permission_single_principal'),
        ),
    ]
