# Generated by Django 5.2.4 on 2026-02-06 21:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_folder_activity_folder_group_folderpermission_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="folder",
            name="unique_folder_name_per_parent",
        ),
        migrations.RemoveConstraint(
            model_name="folderpermission",
            name="unique_folder_principal",
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("owner", "parent", "name"),
                name="unique_folder_name_per_parent",
            ),
        ),
        migrations.AddConstraint(
            model_name="folder",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("owner", "name"),
                name="unique_root_folder_name_per_owner",
            ),
        ),
        migrations.AddConstraint(
            model_name="folderpermission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("principal_type", "user")),
                fields=("folder", "user"),
                name="unique_folder_user_permission",
            ),
        ),
        migrations.AddConstraint(
            model_name="folderpermission",
            constraint=models.UniqueConstraint(
                condition=models.Q(("principal_type", "group")),
                fields=("folder", "group"),
                name="unique_folder_group_permission",
            ),
        ),
        migrations.AddConstraint(
            model_name="folderpermission",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("user__isnull", False), ("group__isnull", True)),
                    models.Q(("user__isnull", True), ("group__isnull", False)),
                    _connector="OR",
                ),
                name="folder_permission_single_principal",
            ),
        ),
    ]
