# Copyright (c) Soundscape Community Contributors.
# Generated by Django 5.2.4 on 2026-02-24 13:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_folder_models'),
        ('users', '0003_group_groupmembership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='folderpermission',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='folder_permissions', to='users.group'),
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='GroupMembership',
        ),
    ]
